project:
  type: website

website:
  title: "MapAgora Dashboard"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Civic Opportunity Map
        href: map.qmd  
      - text: Civic Opportunity Table
        href: table.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
