project:
  type: website
  resources:
    - raw_data/cnty_counts_cov.csv
    - raw_data/cnty_civic_org_type.csv
    - raw_data/county_lookup.csv

website:
  title: "MapAgora Dashboard"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Civic Opportunity Chatbot
        href: chatbot.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: style.css
